CREATE DATABASE gpu;

GRANT ALL PRIVILEGES ON gpu.* TO user;

USE gpu;

CREATE TABLE gpu (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    brand VARCHAR(50),
    model VARCHAR(50),
    price NUMERIC,
    vram NUMERIC
);
